name: Flutter CI/CD

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.3
      - name: 'Checkout Flutter 3.24.3'
        shell: bash
        run: |
          cd $FLUTTER_ROOT;
          git fetch --tags;
          git checkout 3.24.3;
          flutter --version;
      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run Flutter tests
      - name: Run tests
        run: flutter test

      # Build the app for Android (APK)
      # - name: Build APK
      #   run: flutter build apk --release

      # Build the app for iOS (only works on macOS)
      # Uncomment this block if you are using macOS runners
      #- name: Build iOS
      #  run: flutter build ios --release --no-codesign

      # Store build artifacts (e.g., APKs)
      # - name: Upload APK
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: app-release.apk
      #     path: build/app/outputs/flutter-apk/app-release.apk
