name: Push Build to Widgetbook Cloud

on:
  push:
    branches:
      - "**"

jobs:
  push-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Checkout Flutter 3.24.3'
        shell: bash
        run: |
          cd $FLUTTER_ROOT;
          git fetch --tags;
          git checkout 3.24.3;
          flutter --version;

      - name: Install dependencies
        shell: bash
        run: |
          flutter pub get
          flutter pub run intl_utils:generate

      - name: Install Widgetbook CLI
        run: dart pub global activate widgetbook_cli

      - name: Push Build
        run: widgetbook cloud build push --api-key ${{ secrets.WIDGETBOOK_CLOUD_API_KEY }} 