name: Push Build to Widgetbook Cloud

on:
  push:
    branches:
      - "**"

jobs:
  push-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.3
      - name: 'Checkout Flutter 3.24.3'
        shell: bash
        run: |
          cd $FLUTTER_ROOT;
          git fetch --tags;
          git checkout 3.24.3;
          flutter --version;

      - name: Install dependencies
        shell: bash
        run: |
          flutter pub get
          flutter pub run intl_utils:generate
          dart run build_runner build -d

      - name: Install Widgetbook CLI
        run: dart pub global activate widgetbook_cli

      - name: Push Build
        run: widgetbook cloud build push --api-key ${{ secrets.WIDGETBOOK_CLOUD_API_KEY }} 